# Generated by Django 6.0.5 on 2026-05-18 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('ANNOUNCEMENT', "E'lon"), ('NEWS', 'Yangilik'), ('WARNING', 'Ogohlantirish'), ('APPLICATION_RESPONSE', 'Ariza javobi'), ('SYSTEM', 'Tizim'), ('DIRECT_MESSAGE', 'Xabar'), ('NEW_ORDER', 'Yangi buyurtma'), ('CONFIRMATION_REQUEST', 'Tasdiqlash'), ('DISPUTE', 'Shikoyat')], default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
