export const SOCKET_EVENTS = {
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  NOTIFICATION: 'NOTIFICATION',
} as const;

export type SocketEvent = typeof SOCKET_EVENTS[keyof typeof SOCKET_EVENTS];
