# Generated by Django 6.0.5 on 2026-05-18 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('ACCEPTED', 'Qabul qilindi'), ('CHATTING', 'Chat'), ('REJECTED', 'Rad etildi'), ('IN_PROGRESS', 'Jarayonda'), ('AWAITING_CONFIRMATION', 'Tasdiqlash kutilmoqda'), ('COMPLETED', 'Yakunlandi'), ('FAILED', 'Muvaffaqiyatsiz'), ('DISPUTED', 'Shikoyat'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=30)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=300)),
                ('preferred_date', models.DateTimeField(blank=True, null=True)),
                ('is_successful', models.BooleanField(blank=True, null=True)),
                ('auto_completed', models.BooleanField(default=False)),
                ('awaiting_confirm_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='providers.providerprofile')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('from_role', models.CharField(choices=[('USER', 'Foydalanuvchi'), ('PROVIDER', 'Provayder')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.skill')),
            ],
        ),
    ]
