import { Provider } from '@/src/types';
import { Role, UserStatus, AvailabilityStatus, ServiceType, DayOfWeek } from '@/src/types/enums';

// High-fidelity local mock data representing Tashkent specialists
export const MOCK_PROVIDERS: Provider[] = [
  {
    id: 1,
    user: {
      id: 'usr_001',
      wallet_id: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
      first_name: 'Farxod',
      last_name: 'Alimov',
      username: 'farxod_plumber',
      email: 'farxod.plumber@gmail.com',
      role: Role.PROVIDER,
      status: UserStatus.ACTIVE,
      is_online: true,
      avatar: null,
      created_at: '2026-01-10T12:00:00Z',
      updated_at: '2026-05-10T12:00:00Z',
    },
    bio: 'Professional santexnika xizmatlari. 10 yildan ortiq tajriba. Quvurlar o\'rnatish, ta\'mirlash va kranlarni almashtirish.',
    availability_status: AvailabilityStatus.AVAILABLE,
    reliability: 98,
    successful_orders: 142,
    failed_orders: 2,
    created_at: '2026-01-11T09:00:00Z',
    skills: [
      {
        id: 101,
        provider: 1,
        skill: {
          id: 10,
          category: 1,
          name: 'Santexnika',
          description: 'Santexnika ishlari va ta\'mirlash',
          is_active: true,
          created_at: '2026-01-01T00:00:00Z',
        },
        service_type: ServiceType.BOTH,
        experience_years: 11,
        price_from: '50000',
        price_to: '150000',
        description: 'Barcha turdagi santexnika ishlari kafolatlangan holda',
      },
    ],
    districts: [
      { id: 201, provider: 1, district_name: 'Yunusobod' },
      { id: 202, provider: 1, district_name: 'Chilonzor' },
    ],
    schedule: [
      { id: 301, provider: 1, day_of_week: DayOfWeek.MONDAY, open_time: '09:00', close_time: '18:00', is_active: true },
      { id: 302, provider: 1, day_of_week: DayOfWeek.TUESDAY, open_time: '09:00', close_time: '18:00', is_active: true },
      { id: 303, provider: 1, day_of_week: DayOfWeek.WEDNESDAY, open_time: '09:00', close_time: '18:00', is_active: true },
      { id: 304, provider: 1, day_of_week: DayOfWeek.THURSDAY, open_time: '09:00', close_time: '18:00', is_active: true },
      { id: 305, provider: 1, day_of_week: DayOfWeek.FRIDAY, open_time: '09:00', close_time: '18:00', is_active: true },
    ],
  },
  {
    id: 2,
    user: {
      id: 'usr_002',
      wallet_id: '0x3as78fD98A78dD9B18aB90de82D98c9f28D890a2',
      first_name: 'Jasur',
      last_name: 'Rustamov',
      username: 'jasur_electro',
      email: 'jasur.rustamov@gmail.com',
      role: Role.PROVIDER,
      status: UserStatus.ACTIVE,
      is_online: true,
      avatar: null,
      created_at: '2026-02-15T12:00:00Z',
      updated_at: '2026-05-12T12:00:00Z',
    },
    bio: 'Har qanday murakkablikdagi elektr montaj ishlari. Uy va ofislar uchun xavfsiz va tezkor xizmat ko\'rsataman.',
    availability_status: AvailabilityStatus.AVAILABLE,
    reliability: 95,
    successful_orders: 87,
    failed_orders: 3,
    created_at: '2026-02-16T10:00:00Z',
    skills: [
      {
        id: 102,
        provider: 2,
        skill: {
          id: 11,
          category: 2,
          name: 'Elektr xizmatlari',
          description: 'Rozetkalar, qandillar, montaj ishlari',
          is_active: true,
          created_at: '2026-01-01T00:00:00Z',
        },
        service_type: ServiceType.ONSITE,
        experience_years: 6,
        price_from: '80000',
        price_to: '200000',
        description: 'Yuqori kuchlanishli tarmoqlarni montaj qilish va ta\'mirlash',
      },
    ],
    districts: [
      { id: 203, provider: 2, district_name: 'Mirzo Ulug\'bek' },
      { id: 204, provider: 2, district_name: 'Mirobod' },
    ],
    schedule: [
      { id: 306, provider: 2, day_of_week: DayOfWeek.MONDAY, open_time: '08:00', close_time: '20:00', is_active: true },
      { id: 307, provider: 2, day_of_week: DayOfWeek.WEDNESDAY, open_time: '08:00', close_time: '20:00', is_active: true },
      { id: 308, provider: 2, day_of_week: DayOfWeek.FRIDAY, open_time: '08:00', close_time: '20:00', is_active: true },
    ],
  },
  {
    id: 3,
    user: {
      id: 'usr_003',
      wallet_id: '0x99A8c89bA90D78ad1B71109aAb0deA45F6e89791',
      first_name: 'Madina',
      last_name: 'Shirova',
      username: 'madina_clean',
      email: 'madina.cleaning@gmail.com',
      role: Role.PROVIDER,
      status: UserStatus.ACTIVE,
      is_online: false,
      avatar: null,
      created_at: '2026-03-01T12:00:00Z',
      updated_at: '2026-05-15T12:00:00Z',
    },
    bio: 'Gipoallergenik vositalar bilan uylarni professional tozalash (eco-cleaning). Sifatga 100% kafolat beriladi.',
    availability_status: AvailabilityStatus.AVAILABLE,
    reliability: 92,
    successful_orders: 54,
    failed_orders: 4,
    created_at: '2026-03-02T11:00:00Z',
    skills: [
      {
        id: 103,
        provider: 3,
        skill: {
          id: 12,
          category: 3,
          name: 'Tozalash',
          description: 'Uylarni tozalash xizmatlari',
          is_active: true,
          created_at: '2026-01-01T00:00:00Z',
        },
        service_type: ServiceType.ONSITE,
        experience_years: 4,
        price_from: '100000',
        price_to: '300000',
        description: 'Boshlang\'ich va chuqur (general) tozalash ishlari',
      },
    ],
    districts: [
      { id: 205, provider: 3, district_name: 'Yashnobod' },
      { id: 206, provider: 3, district_name: 'Sergeli' },
    ],
    schedule: [
      { id: 309, provider: 3, day_of_week: DayOfWeek.SATURDAY, open_time: '10:00', close_time: '19:00', is_active: true },
      { id: 310, provider: 3, day_of_week: DayOfWeek.SUNDAY, open_time: '10:00', close_time: '19:00', is_active: true },
    ],
  },
  {
    id: 4,
    user: {
      id: 'usr_004',
      wallet_id: '0x123A8Cdf890A90efDa12B890aAbceBDE7d89D91A',
      first_name: 'Diyorbek',
      last_name: 'Ismoilov',
      username: 'diyor_repair',
      email: 'diyor.repairs@gmail.com',
      role: Role.PROVIDER,
      status: UserStatus.ACTIVE,
      is_online: true,
      avatar: null,
      created_at: '2026-03-15T12:00:00Z',
      updated_at: '2026-05-18T12:00:00Z',
    },
    bio: 'Muzlatgich, kir yuvish mashinalari va konditsionerlarni sifatli ta\'mirlash. Ehtiyot qismlari o\'zimizdan.',
    availability_status: AvailabilityStatus.AVAILABLE,
    reliability: 100,
    successful_orders: 198,
    failed_orders: 0,
    created_at: '2026-03-16T12:00:00Z',
    skills: [
      {
        id: 104,
        provider: 4,
        skill: {
          id: 13,
          category: 4,
          name: 'Maishiy texnika ta\'mirlash',
          description: 'Muzlatgich va kir yuvish mashinalari',
          is_active: true,
          created_at: '2026-01-01T00:00:00Z',
        },
        service_type: ServiceType.BOTH,
        experience_years: 8,
        price_from: '70000',
        price_to: '250000',
        description: 'Murakkab elektron platalarni ta\'mirlash kafolati bilan',
      },
    ],
    districts: [
      { id: 207, provider: 4, district_name: 'Olmazor' },
      { id: 208, provider: 4, district_name: 'Uchtepa' },
    ],
    schedule: [
      { id: 311, provider: 4, day_of_week: DayOfWeek.MONDAY, open_time: '09:00', close_time: '20:00', is_active: true },
      { id: 312, provider: 4, day_of_week: DayOfWeek.TUESDAY, open_time: '09:00', close_time: '20:00', is_active: true },
      { id: 313, provider: 4, day_of_week: DayOfWeek.WEDNESDAY, open_time: '09:00', close_time: '20:00', is_active: true },
      { id: 314, provider: 4, day_of_week: DayOfWeek.THURSDAY, open_time: '09:00', close_time: '20:00', is_active: true },
      { id: 315, provider: 4, day_of_week: DayOfWeek.FRIDAY, open_time: '09:00', close_time: '20:00', is_active: true },
      { id: 316, provider: 4, day_of_week: DayOfWeek.SATURDAY, open_time: '09:00', close_time: '18:00', is_active: true },
    ],
  },
  {
    id: 5,
    user: {
      id: 'usr_005',
      wallet_id: '0x992B9C89daBAc8eEFDa787C1890DeB1123D8A901',
      first_name: 'Dilshod',
      last_name: 'Karimov',
      username: 'dilshod_cargo',
      email: 'dilshod.cargo@gmail.com',
      role: Role.PROVIDER,
      status: UserStatus.ACTIVE,
      is_online: true,
      avatar: null,
      created_at: '2026-04-01T12:00:00Z',
      updated_at: '2026-05-19T12:00:00Z',
    },
    bio: 'Yuk tashish va yuk mashinasi xizmatlari (Ford Transit). Toshkent shahri va viloyatlar bo\'ylab yuklarni yetkazish.',
    availability_status: AvailabilityStatus.BUSY,
    reliability: 88,
    successful_orders: 120,
    failed_orders: 16,
    created_at: '2026-04-02T10:00:00Z',
    skills: [
      {
        id: 105,
        provider: 5,
        skill: {
          id: 14,
          category: 5,
          name: 'Yuk tashish',
          description: 'Yuk mashinasi va mebellarni tashish',
          is_active: true,
          created_at: '2026-01-01T00:00:00Z',
        },
        service_type: ServiceType.ONSITE,
        experience_years: 5,
        price_from: '120000',
        price_to: '400000',
        description: 'Mebel va og\'ir yuklarni xavfsiz qadoqlash hamda tashish',
      },
    ],
    districts: [
      { id: 209, provider: 5, district_name: 'Shayxontohur' },
      { id: 210, provider: 5, district_name: 'Yakkasaroy' },
    ],
    schedule: [
      { id: 317, provider: 5, day_of_week: DayOfWeek.MONDAY, open_time: '08:00', close_time: '22:00', is_active: true },
      { id: 318, provider: 5, day_of_week: DayOfWeek.TUESDAY, open_time: '08:00', close_time: '22:00', is_active: true },
      { id: 319, provider: 5, day_of_week: DayOfWeek.WEDNESDAY, open_time: '08:00', close_time: '22:00', is_active: true },
      { id: 320, provider: 5, day_of_week: DayOfWeek.THURSDAY, open_time: '08:00', close_time: '22:00', is_active: true },
      { id: 321, provider: 5, day_of_week: DayOfWeek.FRIDAY, open_time: '08:00', close_time: '22:00', is_active: true },
      { id: 322, provider: 5, day_of_week: DayOfWeek.SATURDAY, open_time: '08:00', close_time: '22:00', is_active: true },
      { id: 323, provider: 5, day_of_week: DayOfWeek.SUNDAY, open_time: '08:00', close_time: '22:00', is_active: true },
    ],
  },
];
